name: PR Check

on: pull_request
jobs:
  check: 
    name: Check build, lint, test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm run setup

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test